telegram:
  token: 1630130884:AAGV0QBhx5frS9HzerH-9qnj4Y1SKGdZrmw      # Telegram bot tokens look like this: 113031530:AAH_4c5Gt9gsVu82OVNjUV7poU7PodYiNsA
  useFirstNameInsteadOfUsername: false
  colonAfterSenderName: false
  skipOldMessages: true
  sendEmojiWithStickers: true
discord:
  useNickname: false
  token: ODE1MTMwNjIwNTY0MDc4NTky.YDn7jA.26SWUZYG7s20aTMWnkdrB2btN7c       # Discord bot tokens look like this: MjI3MDA1NzIvOBQ2MzAzMiMz.DRf-aw.N0MVYtDxXYPS>
  skipOldMessages: true
  replyLength: 100
  maxReplyLines: 2
bridges:
  - name: First bridge
    direction: t2d
    telegram:
      chatId: -1001318020194  # Remember that Telegram group and channel IDs are negative. Include the `-` if you are bridging a group or a channel
      relayJoinMessages: false
      relayLeaveMessages: false
      sendUsernames: false
      relayCommands: false
      crossDeleteOnDiscord: true
    discord:
      channelId: '795906012720005140'       # This ID must be wrapped in single quotes. Example: '244791815503347712'
      relayJoinMessages: false
      relayLeaveMessages: false
      sendUsernames: false
      crossDeleteOnTelegram: true
debug: false
scrapper:
  url: 'https://cointelegraph.com/rss'
  userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36'
  chatID:
    telegram: [-1001319441336] # Remember that Telegram group and channel IDs are negative. Include the `-`
    discord: ['795906012720005140', '796511430764527627'] #ID must be wrapped in single quotes. Example: '244791815503347712'
  loop: 5 #Number of minutes for the bot to search for new updates
  startLastBuildDate: ''