telegram:
  token: 1547550416:AAEF-CeAVJT_2YImEAuMlFBu_xWB1RErP9w      # Telegram bot tokens look like this: 113031530:AAH_4c5Gt9gsVu82OVNjUV7poU7PodYiNsA
  useFirstNameInsteadOfUsername: false
  colonAfterSenderName: false
  skipOldMessages: true
  sendEmojiWithStickers: true
discord:
  useNickname: false
  token: ODIxOTc0NDI5NzE3ODg5MDY1.YFLhVw.jGVyviIFZGy3Jv6Lis-Rs29zM_w       # Discord bot tokens look like this: MjI3MDA1NzIvOBQ2MzAzMiMz.DRf-aw.N0MVYtDxXYPSQew4g2TPqvQve2c
  skipOldMessages: true
  replyLength: 100
  maxReplyLines: 2
bridges:
  - name: First bridge
    direction: both
    telegram:
      chatId: -1001437137705  # Remember that Telegram group and channel IDs are negative. Include the `-` if you are bridging a group or a channel
      relayJoinMessages: true
      relayLeaveMessages: true
      sendUsernames: true
      relayCommands: true
      crossDeleteOnDiscord: true
    discord:
      channelId: '821981383521206293'       # This ID must be wrapped in single quotes. Example: '244791815503347712'
      relayJoinMessages: true
      relayLeaveMessages: true
      sendUsernames: true
      crossDeleteOnTelegram: true
debug: false
scrapper:
  url: 'https://cointelegraph.com/rss'
  userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36'
  chatID:
    telegram: [-529218389] # Remember that Telegram group and channel IDs are negative. Include the `-`
    discord: ['821981383521206293', '822000783468789770'] #ID must be wrapped in single quotes. Example: '244791815503347712'
  loop: 5 #Number of minutes for the bot to search for new updates
  startLastBuildDate: ''